from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# ==========================================
# 1. CLIENT INCOMING PAYLOAD SCHEMAS
# ==========================================

class TargetPreferences(BaseModel):
    target_role: str = Field(..., description="Target role (e.g., Google Cloud FDE, Senior SWE)")
    target_location: Optional[str] = Field("Remote", description="Preferred geographic or office location")
    strict_ats_matching: bool = Field(True, description="If True, forces rigid keyword compliance over soft semantics")

class ClientApplicationPayload(BaseModel):
    """Rigid validation schema for initial gateway entry points."""
    raw_text_resume: str = Field(..., min_length=100, description="The full string content extracted from the candidate's resume")
    raw_job_description: str = Field(..., min_length=50, description="The raw target job description text")
    preferences: TargetPreferences = Field(default_factory=TargetPreferences)

    model_config = {
        "json_schema_extra": {
            "example": {
                "raw_text_resume": "Jane Doe. Experienced Software Engineer with 3 years coding in Python...",
                "raw_job_description": "Minimum qualifications: Bachelor's degree in CS... Experience with LangGraph...",
                "preferences": {
                    "target_role": "Forward Deployed Engineer",
                    "target_location": "Bengaluru",
                    "strict_ats_matching": True
                }
            }
        }
    }


# ==========================================
# 2. GRANULAR STRUCTURAL SUB-COMPONENTS
# ==========================================

class AgentLog(BaseModel):
    """Rigid logging schema tracking ReAct execution patterns for explainable audit trails."""
    agent_id: str = Field(..., description="The unique identifier of the active execution node")
    thought: str = Field(..., description="Inside-node reasoning sequence")
    action: str = Field(..., description="External action or tool call executed")
    observation: str = Field(..., description="Outcome of the action execution")
    reflection: str = Field(..., description="Reflective adjustment sequence")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp")


class SemanticGapAnalysis(BaseModel):
    """Structural payload containing sparse & dense gap modeling outputs."""
    ats_score: float = Field(..., description="Evaluated ATS match index scoring metric (0.0 to 1.0)")
    hard_skills_missing: List[str] = Field(default_factory=list, description="Missing tactical tech stack items")
    soft_skills_missing: List[str] = Field(default_factory=list, description="Missing behavioral or methodology items")
    semantic_distance: float = Field(..., description="Cosine distance calculated between target and candidate")


class ReflectionValidation(BaseModel):
    """Integrity score generated by the verification guardrail."""
    is_valid: bool = Field(..., description="Flag indicating if quality gating passes requirements")
    hallucination_flag: bool = Field(False, description="True if ungrounded assertions are detected in generated draft")
    star_method_coverage: float = Field(..., description="Quantified STAR format rule matching score (0.0 to 1.0)")
    improvements_requested: List[str] = Field(default_factory=list, description="Iterative adjustments feedback payload")


# ==========================================
# 3. GLOBAL TRANSACTSTATE MATRIX
# ==========================================

class HiroPlatformState(TypedDict):
    """
    Global Transactional State matrix tracking continuous values across all LangGraph nodes.
    Maintains clean serialization and isolated transactional execution path.
    """
    # Raw Candidate and Target Inputs
    resume_snapshot: str
    job_profile: str
    config: Optional[Dict[str, Any]]
    
    # Additional Enterprise Payload Keys
    raw_job_description: Optional[str]
    raw_resume: Optional[str]
    user_metadata: Optional[Dict[str, Any]]
    dense_sparse_rag_payload: Optional[Dict[str, Any]]
    resume_changelog: Optional[List[str]]
    
    # Processed Metadata & Semantic Layers
    extracted_target_keywords: List[str]
    detected_gaps: List[str]
    initial_ats_score: float
    semantic_analysis: Optional[SemanticGapAnalysis]
    
    # State Drafts & Active Iterative Payloads
    current_resume_draft: str
    current_optimized_resume: str
    reflection_report: Optional[ReflectionValidation]
    reflection_critique: str
    
    # Flow Controller & Infrastructure Variables
    iteration_count: int
    max_iterations: int
    total_tokens_consumed: int
    execution_logs: List[str]
    agent_execution_logs: List[AgentLog]
